### ISSUE TITLE
Web - Horarios que se pisan - servicio

### ISSUE THREAD

**Issue by msarfernandez** [letme-ar/shelter#2]
Retomando pruebitas varias me encontré con que puedo pisar horarios... Puse hasta tres reservas en el mismo lapso pasó. Además, no tenía servicio asociado y pasaba igual. Debería validar que tiene que estar asociada a algún servicio.

**Comment by pollitofive** [comment]
Estoy pensando una re estructuración total para que sea mas fácil el tema de horarios. Si querés mañana lo charlamos.

**Comment by pollitofive** [comment]
Ya esta arreglado esto. Después fijate como quedó. Cuando "Arrastra" un horario y pisa otro, es el único caso en el que refresco la pagina, sino, al quedar bien, no hace falta recargar.
