### ISSUE TITLE
Mobile - Ajustes visuales

### ISSUE THREAD

**Issue by msarfernandez** [letme-ar/shelter#3]
- Hay que sacar la magia de que cambie de día deslizando con el dedo, porque está muy sensible, a penas lo tocas se cambia, y hace que tarde.
- El footer debería estar siempre visible, y que los horarios se scrolleen dentro del espacio que queda disponible entre el header y el footer. Actualmente está a lo largo y llegas al footer luego de scrollear toda la lista.
- Pintar las celdas vacías, o sea, los horarios disponibles (como en web).
- Ver la posibilidad de que se agregue tocando en la lista; no como en web, que podés arrastra y todo, pero que al menos te tome el horario de inicio.

**Comment by pollitofive** [comment]
1) Realizado
2) Lo toqué. Igual, no me quedó del todo claro: ¿Porque el menú de arriba no es siempre visible y si debería serlo el footer? De todas maneras, no me quedó del todo bien porque me pisa el horario de las 23:30 hs, ya que no me permite verlo.
3) Lo hice, pero no soy diseñador, si queres decime vos los colores xD
4) Le puse el botón que tiene arriba a cada registro, pero me falta asignarle al combo el horario que selecciona, me queda pendiente para la próxima

**Comment by msarfernandez** [comment]
1) Ok.
2) El menú también tiene que quedar visible todo el tiempo. Y el footer está tapando porque te quedó como flotando... Si yo veo de armar un frontend para eso, después se puede matchear? Así veo de tocarlo un poco yo.
3) No lo veo coloreado, hice reserva y los veo iguales. El color no importa, después se cambia. La cuestión es que quede como en la web, que cuando está tomado el horario están pintadas las celdas (como el Calendar).
4) Estaría bien con eso, igual no funca... je.

**Comment by pollitofive** [comment]
Se ve que me olvidé de subir algún archivo. Hoy a la noche sin falta lo subo.

**Comment by msarfernandez** [comment]
Eso sobre el 4? Lo otro te parece bien?

**Comment by pollitofive** [comment]
Si si, si queres armar vos el front, para mi es mejor, después vemos como juntar todo!

**Comment by pollitofive** [comment]
Ahi está actualizado el 3 y el 4.

**Comment by pollitofive** [comment]
Esto ya esta tambien, creo que terminé mi parte.
