### ISSUE TITLE
Core - re-estructuración de horarios

### ISSUE THREAD

**Issue by msarfernandez** [letme-ar/shelter#4]
Cambiar la manera en que se guardan/consultan los horarios para poder optimizar el tema del validado de reservas para que no que se pisen.
Habría que tener en cuenta, además de la relación horario-id, las relaciones de este con las salas. Lo menciono ante la duda de que no esté contemplado.

**Comment by pollitofive** [comment]
Avancé bastante con esto. Ya valida cuando queres ingresar una nueva, tanto para el calendario responsive como para el web. Lo hace por ahora en lo que es el "agregar" un nuevo evento, no llegué a hacerlo con el actualizar. Tengo un tema que no se bien que pasa porque cuando le das agregar y te tira el primer mensaje de que tenes un error, si seguís apretando el guardar se rompe. No se por que, tengo que buscarle la vuelta. 

Me quedan pendiente estas cosas, mas lo que vos encuentres.

**Comment by pollitofive** [comment]
Quiero que notes la hora que termino, tenelo en cuenta cuando me pagues... Jajaja.

Ya casi tengo listo el tema de la validación, me falta que valide cuando arrastra la reserva, lo tengo pensado pero me lleva un tiempito y ya es tarde. Estimo que mañana o pasado lo termino, pero fijate como quedó!

**Comment by pollitofive** [comment]
Cuando quise probarlo en el servidor me surgió un error... ¬¬ No funciona aun, bancame hasta mañana

**Comment by msarfernandez** [comment]
Estás a full, sigamos así! Jaja! Ya está subido?

**Comment by pollitofive** [comment]
No no, bancame porque hoy no pude. Cuando llegue hoy a casa veo de arreglarlo, hay una query que me esta rompiendo los huevos!

**Comment by pollitofive** [comment]
Bueno ahora si, podes probarlo, me queda pendiente lo del arrastrar, ahí necesito una horita mínimo

**Comment by pollitofive** [comment]
Ya casi esta terminado esto. Tengo un problema porque por mas que no cambie la reserva en la base, no me termina de quedar bien la reserva en el calendario. Estoy pensando seriamente en refrescar la pagina si se equivoca. Pero chequealo vos cuando puedas y cargame otro requerimiento si es necesario.
